#!/usr/bin/env bash
# build-docker
# build the starfly13 container image

# build starfly13, and tag it as starfly13:GIT_HASH
docker buildx build $@ \
	--file Dockerfile \
	--tag starfly13:latest \
	.

# since we just built starfly13, tag it again by its git hash
# GIT_HASH="$(git log | head -1 | awk -e '{print $2}' | head -c 12)"
# docker image tag starfly13:latest starfly13:${GIT_HASH}
