# ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: tools/starfly/ci/lint.sh

  build_linux:
    name: "Build shiptest.dmb (Linux)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/cache/byond
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-
    - run: tools/starfly/ci/install_byond_linux.sh
    - name: Build Project
      run: |
        source ${HOME}/BYOND/byond/bin/byondsetup
        tools/build/build --ci dm -DCIBUILDING -DCITESTING -DALL_MAPS -DFULL_INIT

  build_windows:
    name: "Build shiptest.dmb (Windows)"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          C:/byond.zip
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-
    - name: Build Project
      run: pwsh tools/starfly/ci/build_windows.ps1
      env:
        DM_EXE: "C:\\byond\\bin\\dm.exe"

  build_auxmos:
    name: "Build libauxmos.so"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/cache/auxmos
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-auxmos-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-auxmos-${{ hashFiles('**/dependencies.sh') }}
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-auxmos-
    - uses: actions/cache/restore@v4
      with:
        path: |
          ${{ github.workspace }}/cache/byond
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
        fail-on-cache-miss: true
    - run: tools/starfly/ci/install_byond_linux.sh
    - run: tools/starfly/ci/build_auxmos.sh

  build_rustg:
    name: "Build librust_g.so"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/cache/rustg
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-rustg-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-rustg-${{ hashFiles('**/dependencies.sh') }}
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-rustg-
    - run: rustup update stable && rustup default stable
    - run: tools/starfly/ci/build_rust_g.sh

  run_integration_tests:
    name: "Integration Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_name:
        - "BASIC_TESTS"
        - "CREATE_AND_DESTROY_TEST"
        - "PLANET_GEN_TEST"
        - "RUIN_PLACEMENT_TEST"
        - "SHIP_PLACEMENT_TEST"

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: oopy-pants
        ports:
          - 23306:3306

    steps:
    - name: "Checkout Project"
      uses: actions/checkout@v4

    - name: "Restore BYOND"
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ github.workspace }}/cache/byond
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
        fail-on-cache-miss: true

    - name: "Restore libauxmos.so"
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ github.workspace }}/cache/auxmos
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-auxmos-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-auxmos-${{ hashFiles('**/dependencies.sh') }}
        fail-on-cache-miss: true

    - name: "Restore librust_g.so"
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ github.workspace }}/cache/rustg
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-rustg-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-rustg-${{ hashFiles('**/dependencies.sh') }}
        fail-on-cache-miss: true

    - name: "Install System Packages"
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update || true
        sudo apt install -o APT::Immediate-Configure=false libssl-dev:i386 libgcc-s1:i386

    - name: "Prepare BYOND"
      run: |
        tools/starfly/ci/install_byond_linux.sh
        cp -v ${{ github.workspace }}/cache/auxmos/libauxmos.so ~/BYOND/byond/bin/libauxmos.so
        cp -v ${{ github.workspace }}/cache/rustg/librust_g.so ~/BYOND/byond/bin/librust_g.so

    # - name: "Debug: Prepare BYOND"
    #   run:
    #     source ~/BYOND/byond/bin/byondsetup
    #     ls -l ~/BYOND/byond/bin && echo
    #     ldd ~/BYOND/byond/bin/DreamDaemon && echo
    #     ldd ~/BYOND/byond/bin/DreamMaker && echo
    #     ldd ~/BYOND/byond/bin/libbyond.so && echo
    #     ldd ~/BYOND/byond/bin/libext.so && echo
    #     ldd ~/BYOND/byond/bin/libauxmos.so && echo
    #     ldd ~/BYOND/byond/bin/librust_g.so && echo

    - name: "Setup MariaDB Database"
      run: |
        mysql --host 127.0.0.1 --port 23306 -u root -poopy-pants -e 'CREATE DATABASE tg_ci;'
        mysql --host 127.0.0.1 --port 23306 -u root -poopy-pants tg_ci < SQL/tgstation_schema.sql

    - name: "Compile Tests"
      run: |
        source ~/BYOND/byond/bin/byondsetup
        tools/build/build --ci dm -DCIBUILDING -DANSICOLORS -D${{ matrix.test_name }}

    - name: "Run Tests"
      run: |
        source ~/BYOND/byond/bin/byondsetup
        bash tools/ci/run_server.sh

  # run_integration_tests:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   services:
  #     mysql:
  #       image: mysql:latest
  #       env:
  #         MYSQL_ROOT_PASSWORD: root
  #       ports:
  #         - 3306
  #       options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup BYOND cache
  #       id: cache-byond
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/BYOND
  #         key: ${{ runner.os }}-byond-cache-${{ secrets.CACHE_PURGE_KEY }}-${{ hashFiles('dependencies.sh') }}-${{ hashFiles('.github/workflows/run_integration_tests.yml') }}

  #     - name: Install BYOND
  #       if: steps.cache-byond.outputs.cache-hit != 'true'
  #       run: bash tools/ci/install_byond.sh

  #     - name: Install runtime dependencies
  #       run: |
  #         sudo dpkg --add-architecture i386
  #         sudo apt update || true
  #         sudo apt install -o APT::Immediate-Configure=false libssl-dev:i386 libgcc-s1:i386

  #     - name: Setup dependencies cache
  #       id: cache-deps
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.byond/bin
  #         key: ${{ runner.os }}-deps-cache-${{ secrets.CACHE_PURGE_KEY }}-${{ hashFiles('dependencies.sh') }}-${{ hashFiles('.github/workflows/run_integration_tests.yml') }}

  #     - name: Install build dependencies
  #       if: steps.cache-deps.outputs.cache-hit != 'true'
  #       run: |
  #         sudo apt install -o APT::Immediate-Configure=false g++-multilib zlib1g-dev:i386
  #         rustup target add i686-unknown-linux-gnu

  #     - name: Build auxmos
  #       if: steps.cache-deps.outputs.cache-hit != 'true'
  #       run: bash tools/ci/build_auxmos.sh

  #     - name: Build rust-g
  #       if: steps.cache-deps.outputs.cache-hit != 'true'
  #       run: bash tools/ci/build_rust_g.sh

  #     - name: Setup database
  #       run: |
  #         sudo systemctl start mysql
  #         mysql -u root -proot -e 'CREATE DATABASE tg_ci;'
  #         mysql -u root -proot tg_ci < SQL/tgstation_schema.sql
  #         mysql -u root -proot -e 'CREATE DATABASE tg_ci_prefixed;'
  #         mysql -u root -proot tg_ci_prefixed < SQL/tgstation_schema_prefixed.sql

  #     - name: Configure version
  #       if: ${{ inputs.major }}
  #       run: |
  #         echo "BYOND_MAJOR=${{ inputs.major }}" >> $GITHUB_ENV
  #         echo "BYOND_MINOR=${{ inputs.minor }}" >> $GITHUB_ENV

  #     - name: Compile Tests
  #       run: |
  #         source $HOME/BYOND/byond/bin/byondsetup
  #         tools/build/build --ci dm -DCIBUILDING -DANSICOLORS -D${{ inputs.arg }}
  #     - name: Run Tests
  #       run: |
  #         source $HOME/BYOND/byond/bin/byondsetup
  #         bash tools/ci/run_server.sh

