# ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    name: "Build (Linux)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/cache/byond
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-
    - run: tools/starfly/ci/install_byond_linux.sh
    - name: Build Project
      run: |
        source ${HOME}/BYOND/byond/bin/byondsetup
        tools/build/build --ci dm -DCIBUILDING -DCITESTING -DALL_MAPS -DFULL_INIT

  build_windows:
    name: "Build (Windows)"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          C:/byond.zip
        key: ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
        restore-keys: |
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-${{ hashFiles('**/dependencies.sh') }}
          ${{ runner.os }}-${{ secrets.CACHE_PURGE_KEY }}-byond-
    - name: Build Project
      run: pwsh tools/starfly/ci/build_windows.ps1
      env:
        DM_EXE: "C:\\byond\\bin\\dm.exe"
